# Site settings
title: Roy Harmon
name: Roy Harmon

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
# - title: Blog
#   url: https://automateddeveloper.blogspot.com/
 - title: GitHub
   url: https://github.com/roy-harmon
# - title: StackOverflow
#   url: https://stackoverflow.com/users/258813/rhinds
# - title: DZone
#   url: https://dzone.com/users/899489/rhinds.html
 - title: LinkedIn
   url: https://www.linkedin.com/in/roy-r-harmon
# - title: Food
#   url: https://www.robbishfood.com/

#Any buzzword skills you want to include
skills:
 - C
 - C#
 - JavaScript
 - Python
 - PHP
 - REST APIs
 - JSON
 - .NET Framework
 - Visual Basic / VBA / VB.NET
 - Java
 - HTML
 - CSS
 - XML
 - SQL
 - Test-Driven Development
 - Object-Oriented Programming
 - Microsoft Office VBA
 - Git / GitHub
 - Laboratory Information Management Systems (LIMS)
 - MS SQL Server
 - MS Access
 - MySQL
 - SQLite

#Blogfeed is optional - including this will add JS to call the feed and populate blog list
#blogfeed: https://automateddeveloper.blogspot.com/feeds/posts/default?alt=json

#Work experience is required
roles:
 - title: Research Assistant
   start: 2014
   end: 2021
   employer: Auburn University
   description: The Auburn University Clinical Pharmacology Laboratory provides drug analysis services for researchers and therapeutic drug monitoring (TDM) for diagnostic laboratories and veterinary practitioners throughout the world. <br />Working as a Research Assistant, I was responsible for all aspects of the TDM service, including management, maintenance, and operation of testing equipment; assisting researchers with pharmacokinetic studies; management of laboratory database systems; web development; implementation of custom software systems (including an in-house LIMS); and automation of research data collection and other laboratory operations via those systems.
 - title: Research Aide
   start: 2010
   end: 2014
   employer: Auburn University
   description: The Auburn University Clinical Pharmacology Laboratory provides drug analysis services for researchers and therapeutic drug monitoring (TDM) for diagnostic laboratories and veterinary practitioners throughout the world. <br />Working as a Research Aide, I was responsible for daily operations of the TDM service; development and validation of new test methods; improving efficiency of laboratory processes; and development of in-house software systems.
# - title: CTO
#   start: 2017
#   end: Ongoing
#   employer: Basement Crowd
#   description: Legaltech startup producing a range of innovative legal products. Products include <a href="https://www.juriosity.com" taget="_blank">Juriosity</a>, <a href="https://www.fromcounsel.com" taget="_blank">FromCounsel</a>, <a href="https://www.sparqa.com" taget="_blank">Sparqa</a>.
# - title: Senior Engineer
#   start: 2016
#   end: 2017
#   employer: Emerald Street Ventures
#   description: Emerald Street Ventures was established as an incubator vehicle for the development of a number of software and legal-tech projects, and a rapidly growing, London-based start-up using innovative technologies to revolutionise and change the software and legal-tech landscape. Working with a range of cutting edge technologies and techniques including Scala, Cassandra, CoreOS, a variety of Machine Learning techniques.
# - title: Senior Engineer
#   start: 2012
#   end: 2016
#   employer: Covestor
#   description: Covestor is an investment marketplace startup that was successfully acquired by Interactive Brokers in 2015. <br/> Working as a senior engineer, I worked closely with the CTO and across the full-stack, I was involved in all aspects of the technology including the website and back-end services.
# - title: Associate Manager
#   start: 2005
#   end: 2012
#   employer: Accenture
#   description: Working on a range of functional and technical roles, primarily working on client sites in Financial Services in London and Europe.

#Education is required
education:
 - level: Master of Science (M.S.)
   date: 2021
   subject: Computer Science and Software Engineering
   school: Auburn University
 - level: Bachelor of Science (B.S.)
   date: 2007
   subject: Biochemistry
   school: Marshall University

#This section is optional (as is the image link below)
#coursera:
#   profileurl: https://www.coursera.org/user/i/c6362b4056f755a04bef6a791a62102b
#   courses:
#    - title: Functional Programming Principles in Scala
#      link: https://www.coursera.org/course/progfun
#      optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/progfun/small-icon.hover.png
#      date: September 16, 2013
#    - title: Algorithms Design and Analysis, Part 1
#      link: https://www.coursera.org/specializations/algorithms
#      optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/algo/small-icon.hover.png
#      date: April 28, 2014

#This section is optional - embeds slideshows from speakerdeck
# to get the speakerdeck ID copy the embed code and look for the data-it attribute
#speakerdeck:
#   profileurl: https://speakerdeck.com/robhinds
#   talks:
#   - title: Product Management for Engineers
#     speakerdeckId: 94f0070c4e434ec79fe9b4eb2cb574e0
#      conference: API Conference, Berlin 2018
#    - title: Agile Machine Learning - from Theory to Production
#      speakerdeckId: ec84f2f56e9743afb0675b1eeeb6b6ce
#      conference: W-JAX Conference, Munich 2017 (London 2017)

#List of interesting Github repo/projects to include - optional
github:
 - roy-harmon/RosieLIS
 - roy-harmon/UniversaLIS
 - roy-harmon/PFogSim-v3
 
#Stackoverflow flair is optional
#stackoverflow:
#   profileurl: https://stackoverflow.com/users/258813/rhinds
#   flairimageurl: https://stackoverflow.com/users/flair/258813.png

intro: |
   I am a software engineer with 11 years of development experience. I am fluent in the most common dialects of Visual Basic (VB6/7, VBA, VB.NET), as well as C#, Java, and T-SQL. I am proficient with Python, JavaScript, C, and PHP. <br /><br />
   I have worked on many projects that facilitated clinical research, optimized laboratory operations, and accelerated data analysis. These projects primarily involved working with relational databases such as Microsoft SQL Server, MySQL, or Microsoft Access. <br /><br />
   Due to medical limitations, I am exclusively looking for a remote work position.
   
#  I am an engineer with 15 years experience working in technology. I have primarily worked on the JVM, but have worked across a broad range of technologies thereon: Java, Groovy, Android, Coldfusion and most recently Scala. As well as spending a reasonable amount of time building applications for the web, which has given me an exposure to a range of javascript technologies over the years, through jQuery, extjs, knockout, backbone and most recently to React. <br/><br/>
#  I enjoy building interesting products, with a good Product Management focus and a good emphasis on good engineering principles and clean code (having worked across differing languages on the JVM, I recognise that good code is contextual).<br/><br/>
#  I have worked in large scale consultancy roles across Europe as well as a mix of startup experience (including one that was acquired) and I am currently the Chief Technology Officer at a legal-tech startup called <a href="https://www.basementcrowd.com" target="_blank">Basement Crowd</a> where we are building innovative products to serve the legal industry.

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   I gained a large portion of my experience while working under the title of "Research Assistant." This title can be misleading; while I certainly have laboratory experience and skills, my role quickly expanded far beyond the original job description due to my flexibility. <br /><br />
   My adaptability is one of my greatest assets, and it shows in my professional development. Initially, my job involved mostly database development and data analysis in addition to sample testing. Over time, I added new tools to my metaphorical toolbox as my work for the laboratory required new skills. <br />
   For example, I learned C# in order to write a Windows service that communicated with the automated analyzer, bridging the gap between the instrument and the lab's database to automatically send test requests and receive results. <br />
   I learned JavaScript and PHP when I saw an opportunity to dramatically cut our data entry overhead with a web-based sample submission system. I started learning Python when I set up a system to monitor lab equipment with a RaspberryPi. <br />
   I expanded my RESTful API skills when a research project required integrating components from at least four separate sources; some of them required OAuth2, but one source lacked an API altogether. That project was full of opportunities to learn. <br /><br /> 
   Over the years, I came to realize that my favorite part of the job was the challenge of finding elegant and robust solutions to complex programming problems. I began to feel the need for a career change. I had been managing databases and writing software for in-house production use for years, but on paper I was still a Research Assistant; I was expected to keep the lab running. While improving operational efficiency and optimizing data flow were essential to meeting that demand, my role in the lab had long since outgrown the job description. However, being self-taught, I still lacked the credentials needed to shift careers. <br />
   Fortunately, I was working at Auburn University, so I was able to take computer science courses while continuing to work my full-time job. After a handful of undergraduate courses to brush up on the fundamentals, I was accepted into the M.S. in Computer Science and Software Engineering graduate program. I started in January 2020 and graduated in December 2021 with a GPA of 3.91. <br /><br />
   Now, I am ready to face new challenges as a software engineer. 
#   <strong>Scala</strong>: My current role uses Scala as the primary language and have been building applications in Scala for the last two years. I am familiar with a range of Scala libraries, such as <a target="_blank" href="https://automateddeveloper.blogspot.com/2017/12/an-opinionated-guide-to-building-apis.html"> Akka-Http for building microservices</a> and <a target="_blank" href="https://automateddeveloper.blogspot.com/2018/09/generic-programming-with-scala.html"> Shapeless for generic programming</a>, as well as familiar with a range of <a target="_blank" href="https://basementcrowd.com/2018/11/28/scala-the-aux-pattern-path-dependent-types/" >functional programming techniques available</a>.<br/><br/>
#   <strong>Java</strong>: I am experienced in a variety of Java APIâ€™s and frameworks. I have worked with Spring 4, Spring Boot, JPA (Hibernate and EclipseLink) in addition to others. <br/><br/>
#  <strong>Groovy</strong> I have used Groovy as a language in production for ~4 years and I am familiar with many of the languages features (such as writing <a target='_blank' href="https://dzone.com/articles/functional-programming-groovy">Functional Programming style groovy</a>) and quirks (such as <a target="_blank" href="https://dzone.com/articles/groovy-retrospective-an-addendum-memory-usage-perm">memory leak issues</a>). <br/><br/>
#  <strong>Cloud platforms</strong>: I have primarily used AWS for running production apps on the cloud. I have experience setting up, configuring and running applications using a range of AWS offerings, including EC2, RDS, S3, Cogito, <a target="_blank" href="https://automateddeveloper.blogspot.com/2018/05/serverless-with-aws-lambda-scala.html">Lambda</a> and its more recent <a target="_blank" href="https://automateddeveloper.blogspot.com/2018/10/machine-learning-with-aws-scala.html">Machine Learning capabilities</a>.<br/><br/>
#   <strong>Web Development</strong>: Through building web applications, I have also worked with various client side technology, having used jQuery, Bootstrap, LESS, SASS, Backbone/Underscore/Require. More recently I have written React applications (primarily using the Create React App framework, and extending them)<br/><br/>
#  <strong>Development Control</strong>: I have a good knowledge of application life-cycle management and have worked with SVN, Git, Maven, Gradle, Sonar, Jenkins, TeamCity, etc. I have experience with an array of testing tools and technologies.<br/><br/>
#   I have also gained experience and knowledge of other technologies from several side projects and research that I have undertaken in my free time, including Android, a variety of social APIs (Twitter etc) and cloud platforms such as CloudFoundry/OpenShift/AppFog/AWS. <br/><br/>
#   As part of Nerdability, I created, and am now primary contributor to, two Spring projects - <a target='_blank' href="https://github.com/robhinds/spring-social-geeklist">Spring-Social-Geeklist</a> and <a target='_blank' href="https://github.com/nerdability/spring-social-khan-academy">Spring-Social-Khan-Academy</a>, which provide core integration with those third-party APIs on top of the Spring Social framework. They are both listed as community projects: <a target='_blank' href="https://projects.spring.io/spring-social/">https://projects.spring.io/spring-social/</a>. <br/><br/>
#   I write a blog covering technical and opinion articles that can be found here: <a target='_blank' href="https://automateddeveloper.blogspot.com/">automateddeveloper.blogspot.com</a> (I am also a <a target='_blank' href="https://dzone.com/users/899489/rhinds.html">DZone MVB</a>)
